RetroAchievements/RALibretro

Makefile
With this Makefile I am able to [cross-]compile RALibretro on Linux and Windows/MSYS2.
Regarding the compilation on Windows/MSYS2, it doesn't change anything. Everything works in the same way.
For cross compiling on Linux it's needed to have the toolchain for cross compiling (of course) and the SDL2 mingw development libraries installed (which can be found [here](https://www.libsdl.org/download-2.0.php)).
**NOTE**: looks like the `libstdc++-6.dll` provided by the `g++-mingw-w64-i686` package on Ubuntu-based distros is different than the one native from Windows. Then I had to use `-static-libstdc++` when cross compiling.
**EDIT**: I was having issues to launch RALibretro after cross-compiling, but solved it by using the static linking trick described above.
=> able to cross compile RALibretro on Linux

.gitattributes, .gitignore, README.md, dl-cores.bat
CRLF line endings are used in `dl-cores.bat` for compatibility reasons, and enforced in `.gitattributes` to avoid automatic conversions on Windows.
`wget` and `unzip` must be provided by the user.
Closes #36, and possibly #31 (please confirm).
=> Add core fetching script for Windows

src/Emulator.h
This system name must be fixed, so it does link to proper console id 14 "Neo Geo Pocket" instead of 32 called "Neo Geo", that should be used for CD i suppose
=> Fixed neogeo pocket system name for proper console linkage

src/RALibretro.vcxproj
fixes missing DLL error on machines where VS2015 redistributable has not yet been installed.
=> static link to MSVCP140

src/Emulator.cpp, src/menu.rc
This PR solves the issue started on commit 127a28784f5247acd757959a9a1f935c95aa8a2c. That commit removes [lines like this one](https://github.com/RetroAchievements/RALibretro/commit/127a28784f5247acd757959a9a1f935c95aa8a2c#diff-73463b17d9ee77f556b8ab8f50175adaL294), and in this PR I'm putting them back where they are still necessary.
(Thanks @Jamiras for pointing where the problem is.)
I've tested this change with games for all supported cores and it works fine.
It was **not** noticed in 1.0.7 (current released version) because the branch with the buggy commit had not yet been merged in the `master` branch (used to build the officially released version), but only in the `develop` one.
In this PR I'm also removing the "Mednafen PSX" from the "Select Core" menu.
=> load ROM data before RA_OnLoadNewRom() (and free memory right after)

src/Emulator.cpp, src/Util.cpp, src/Util.h
Tested with several headered NES ROMs, and one FDS ROM. 
Headerless ROM still does not work. The FCEUMM core doesn't support headerless ROMs:
> [WARN] Missing header or invalid iNES format file!
This solution also eliminates the need for the power of 2 rounding required by original hashing (FCEUX would read Action 52 as a 2MB PRG, even though it's only 1.5MB).
=> include CHR data in NES hash

src/Application.cpp
I believe multiple cores require system files, and since a load failure results in a subsequent crash (#39), we should tell the user to restart regardless of where the problem comes from.
=> Display an error message on load failure for all cores

src/RALibretro.vcxproj
I get a linking error with it, and can compile without a problem without, so I assume it is not needed. Otherwise a corresponding instruction is needed in the compilation information.
=> Remove link to dxguid.lib

src/Emulator.cpp
This PR checks the existence of a valid header to skip it if it is present, and hashes the rest of the file. With an untouched rip the resulting hash matches databases.
I also removed a file size check, because it is redundant (no commercial Lynx release exceeds 512KB), potentially error-inducing (if homebrew releases exceed that size) and confusing.
Please update https://github.com/RetroAchievements/docs/wiki/Game-Identification/ once merged/released.
I also have a RetroArch PR that I will send after this one is processed.
=> Support headerless Lynx files

src/menu.rc
Just a small change on the menu listing Konami, Cave and Psikyo as supported arcade boards:
=> listing Konami/Cave/Psikyo as supported by fbalpha

src/menu.rc
Reverts RetroAchievements/RALibretro#61
Many Cave/Psikyo games are vertical shmups and RALibretro doesn't rotate the screen properly.
Also, @JuliaWolska (aka Salsa) reported that many Konami games are unstable.
That being said, maybe it's better to not advertise the support for those boards so soon.
=> Revert "listing Konami/Cave/Psikyo as supported by fbalpha"

src/Application.cpp, src/Application.h, src/Emulator.cpp, src/Emulator.h, src/RALibretro.vcxproj, src/RALibretro.vcxproj.filters, src/Util.cpp, src/Util.h
Relies on the core's `info->need_fullpath` parameter. If that is false, we can unzip the file and load it directly into the core. If it's true, we have to let the core tell us which files it supports. The "Open Game" dialog will include 'zip' in the "Supported Files" selection if the core supports the functionality.
NOTE: if a zip file contains more than one file or any sort of directory structure, it will not load. The zip processing logic is very simple.
The following cores now support zip files:
* FCEUmm
* Gambatte
* Mednafen VB
* mGBA
* Snes9x
* Stella
* ProSystem
The following cores still do not support zip files:
* Beetle SGX
* Genesis Plus GX
* Handy
* Mednafen NGP
* PicoDrive
NOTE: PicoDrive says it needs the full path, so this code prevents loading zip files for that core, but …
=> support for zipped ROMs (implements #4)

src/Application.cpp, src/Application.h, src/Fsm.cpp, src/Fsm.fsm, src/RA_Implementation.cpp, src/Util.cpp, src/main.cpp
* pass ROM name to unknown game dialog
* make Pause on Reset/Trigger actually pause the emulator
* allow turbo in hardcore
* don't allow stepping when paused in hardcore
also updated the RAIntegration version to pick up the fix for the 12005 error
[RALibRetro-checklist.txt](https://github.com/RetroAchievements/RALibretro/files/3164791/RALibRetro-1.0.15.txt)
=> Complete checklist for RALibRetro

src/components/Logger.cpp, src/libretro/Components.h
After a couple hours of play, my `log.txt` file was over 40MB:
```
$ ls -l log.txt
-rw-r--r-- 1 user user 43566131 Aug  5 17:57 log.txt
```
It was primarily filled with this over and over:
```
[DEBUG] [BRE] Calling libretro::BareCore::run
[DEBUG] [CRE] Calling GET_VARIABLE_UPDATE (17)
[DEBUG] [CRE] Called  GET_VARIABLE_UPDATE (17) -> 1
[DEBUG] [VID] Texture refreshed with 700 x 240 pixels
[DEBUG] [BRE] Called  libretro::BareCore::run
[DEBUG] [AUD] Requested 737 audio frames
[DEBUG] [AUD] Original ratio 1.088435 adjusted by 0.996765 to 1.084914
[DEBUG] [AUD] Resampling 1474 samples to 1600
[DEBUG] [AUD] Resampled  1470 samples to 1600
[DEBUG] [AUD] Requested 3200 bytes but only 2892 available, sleeping
[DEBUG] [AUD] Requested 3200 bytes but only 2892 available, sleeping
[DEBUG] [AUD] …
```
=> don't log DEBUG messages in release build

src/Application.cpp, src/components/Config.cpp, src/components/Config.h, src/menu.rc
Changes
To
Also note the dialog title now reflects the currently loaded core.
=> use multiple columns in core settings dialog if more than 16 variables exist

src/Application.cpp, src/CdRom.cpp, src/CdRom.h, src/Emulator.cpp, src/Util.cpp, src/Util.h
libretro cores support unicode paths in the form of UTF-8. `fopen` and `GetOpenFileName` do not.
When a user tried to load a game from a path containing unicode characters, `GetOpenFileName` would convert the unicode characters to question marks, and `fopen` would not be able to find the file.
This PR replaces `GetOpenFileName` with `GetOpenFileNameW`, so we get back a path containing unicode characters when selecting a game to load. That is then converted to UTF-8 so it can be passed to the core. Additionally, everything previously calling `fopen` now calls `util::openFile`, which will detect the non-ASCII characters and convert the UTF-8 path back to unicode and call `wfopen`.
I've modified the `stbi_` calls to use `util::openFile`, so save state images can also be properly …
=> support for unicode paths

src/Application.cpp, src/Emulator.cpp, src/Emulator.h
fixes issue where toolkit editors were disabled when reloading the current game to refresh leaderboard data.
=> reset activeGame when unloading game

src/Application.cpp, src/Application.h, src/components/Video.cpp, src/libretro/BareCore.cpp, src/libretro/Components.h, src/libretro/Core.cpp
If a core indicates a RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL higher than 10, gameplay rendering switches to a rendering loop that keeps track of how long it takes to process and render each frame. If the render rate is not at least 55 fps, some renders will be dropped to try to keep the processing rate about 55 fps. If that cannot maintain the desired framerate, the user will be informed that they need to adjust their core settings.
This should help users who are experiencing some lag running PSX games. Instead of rendering all 60 frames, we can reactively render 40 or less to keep the number of processed frames at 60.
It seems like this scale is completely arbitrary. FCEUmm (NES) reports 5, Genesis GX Plus reports 7, Snes9x reports 12, mGBA doesn't report anything, and Beetle PSX …
=> process some frames without rendering them to maintain framerate

src/Application.cpp, src/CdRom.cpp, src/CdRom.h, src/Emulator.cpp
Changes the PSX hash from being the MD5 of the boot executable contents to being the MD5 of the concatenation of the boot executable name and it's contents.
Also includes support for CUE/BINs other than MODE2/2352
=> Include boot executable filename in PSX hash

src/CdRom.cpp, src/Emulator.cpp
The "BOOT=" entry for Wild Arms is "EXE\SCUS_946.08", which requires navigating the directory tree.
=> support BOOT executables in subfolder

src/Application.cpp
Once a core is loaded, the RAIntegration User-Agent string is changed from
```RALibRetro/1.0.15.35 (WindowsNT 10.0) Integration/0.76.3.7```
to
```RALibRetro/1.0.15.35 (WindowsNT 10.0) Integration/0.76.3.7 mednafen_psx_libretro/0.9.44.1_3e3acfc```
or something similar
=> include current core version information in User-Agent string

bin/Cores/cores.json, src/Emulator.cpp, src/Emulator.h, src/libretro/BareCore.cpp
Adds support for:
* blueMSX (#93) - Colecovision, SG-1000
* Beetle GBA (#85) - GBA
* Beetle PCE (#90) - PCEngine / TurboGrafx-16
* bsnes-mercury (#81) - SNES
* Gearboy (#82) - GB, GBC
* Gearsystem (#88) - Genesis, Master System, Game Gear
- Note that this core does not support .md files, so I'm not positive that the Genesis functionality is correct, but since it does work with GameGear, I'm giving it the benefit of the doubt
* VBA Next (#84) - GBA
=> Allow more cores to be installed

src/Application.cpp, src/Application.h, src/Emulator.cpp, src/KeyBinds.cpp, src/KeyBinds.h, src/Util.cpp, src/components/Config.cpp, src/components/Config.h, src/components/Dialog.cpp, src/components/Input.cpp, src/components/Input.h
Adds bindings for L3/R3 and left/right analog sticks. 
**Note**: Only analog joystick controls can be mapped to analog sticks. There is no keyboard equivalent.
Also adds "Controller 1" and "Controller 2" selectors in the Core Settings dialog for choosing between controllers supported by the core.
The default controller is "RetroPad", which doesn't have analog support. You must select "DualShock" or one of the "Analog" options _before loading the game_ to enable analog controls in Beetle PSX.
=> Add support for analog controls

bin/Cores/cores.json, src/Emulator.cpp, src/Emulator.h
Implements #114 
The only limitation seems to be that the core doesn't support cue files that reference MP3 audio tracks.
Hashing is done using the same logic as Sega CD. Note that the Sega CD header is 512 bytes, whereas the Saturn header is only 256, but is followed by several KB of executable code, so hashing 512 bytes instead of just 256 will still result in a unique hash. This is an optimization for RetroArch where the hash is calculated without knowing which system it's trying to hash. By using the same hashing algorithm, RetroArch will have one less hash to check.
=> add support for Saturn via Beetle Saturn

src/CdRom.cpp, src/CdRom.h, src/Emulator.cpp
The previous algorithm was to hash the cue file, which required having a specific exact cue file (same filenames, casing, whitespace). This methodology is very error prone.
The new algorithm is similar to the PSX hashing algorithm. A descriptive name is extracted from the disc header, then the boot code is appended to the descriptive name, and the whole thing is hashed. Unlike PSX, the PCE-CD format predates ISO-9660, so there isn't a file system. Instead, the boot code is located by reading data in the disc header.
Additionally, from the CDs that I examined, many of them have smaller than expected boot code blocks, suggesting that the boot code loads and launches additional code. Even with the smaller code blocks, I haven't yet experienced any unexpected collisions. All unique games …
=> update PCEngine-CD hash algorithm

bin/Cores/cores.json, src/Emulator.cpp, src/Emulator.h
Just core enablement. Hashing is entire file. 2MB of system RAM is exposed.
=> add support for Atari Jaguar

src/Application.cpp, src/Application.h
Calls the frame smoothing code for all systems, regardless of how demanding the core claims the system is. 
If the target framerate cannot be achieved, vsync will be disabled. This is important for systems where the target framerate is higher than the monitor refresh rate (WonderSwan runs at 75Hz, most monitors are 60Hz). If the target framerate still cannot be achieved, the existing "emulator disabled" warning will be displayed. 
vsync is re-enabled whenever a game is loaded, and the process restarts.
=> always use frame smoothing; attempt to disable vsync before stopping emulator

bin/Cores/cores.json, src/Emulator.cpp, src/Emulator.h, src/Hash.cpp
From several conversations in discord, apparently this core is fully functional. Hashing is full ROM.
System runs at 72Hz, so it is dependent on the new frame smoothing algorithm to achieve accurate framerates on 60Hz monitors.
=> add support for pokemini core

src/Application.cpp, src/Application.h, src/components/Video.cpp, src/components/Video.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
implements #48 - adds a Rotation option to the Video Settings dialog:
also handles #131 - if the core suggests a rotation for a game, it's automatically applied.
=> add screen rotation to video settings

bin/Cores/cores.json, src/Application.cpp, src/Emulator.cpp, src/Emulator.h, src/Hash.cpp
An NDS ROM has a 0x160 byte header. In this header are pointers to icon/title information and to the boot code for both processors. The hash method that has been derived is to combine the header, the two pieces of boot code and the icon/title information and hash that. In most cases, this results in around 1MB of the file being hashed.
Additionally, support for SuperCard formatted ROMs was added. SuperCard ROMs have an additional 512 byte header prepended to the normal ROM. There isn't really any good documentation of the SuperCard header, so there's a small chance one might not be recognized. If that occurs, we can instruct the user to remove the 512 byte header and the normal ROM should be recognized. Note that DeSMuME does not currently support SuperCard formatted ROMs, so this feature …
=> Updated NDS hashing algorithm

src/Application.cpp, src/KeyBinds.cpp, src/KeyBinds.h, src/components/Input.cpp, src/components/Input.h
Every time the controller reconnects, SDL assigns it a new ID. Because the key binds are looking for a specific ID in case the user has multiple controllers, this breaks the bindings and the controller no longer appears to function. It does function, but needs to be rebound. This is not a pleasant (or obvious) user experience.
I've modified the logic that detects the reconnected controller to map the controller's GUID to the old ID and tell the binding code that the new ID maps to the old ID so the bindings will continue to work.
=> better handling of gamepad reconnect

bin/Cores/cores.json, src/Application.cpp
seems to expose the memory correctly, but doesn't function as well as desmume in demanding 3D scenes. including it as an alternative primarily for debugging.
=> add melonDS core

src/libretro/Core.cpp
relies on https://github.com/RetroAchievements/RAIntegration/pull/500. will return blank without it.
=> automatically pull username from RA DLL for cores that request it

src/Application.cpp, src/libretro/Core.cpp, src/libretro/Core.h
fixes issue where DeSmuMe core was not honoring "Firmware Language" setting
=> seprate initCore from loadCore so configs are available in initCore

src/Application.cpp, src/components/Config.cpp, src/components/Config.h, src/components/Input.cpp
Fixes #158 
I suspect this was broken by #148, but I'm not 100% certain on that. By changing the timing of when the config is loaded, the input structures may not have been initialized, leading to the variables for the controllers not being defined.
I've moved the logic that defines the variables for the controllers into the code that shows the dialog. Additionally, I've updated the code to display the core-specific controller name instead of RetroPad when the core provides a specific label.
I've also updated the code to allow hot-swapping controllers (changing the value without resetting the emulator).
=> ensure controller variables exist for config dialog

bin/Cores/cores.json
FBNeo supports 7z internally. I've tested to verify they load correctly.
=> Add 7z to FBNeo supported extensions

.editorconfig, src/Application.cpp, src/KeyBinds.cpp, src/KeyBinds.h, src/components/Input.cpp, src/components/Input.h, src/libretro/Core.cpp, src/libretro/libretro.h
By default, hotkeys are given precedence over keyboard input. Only if a key press is not handled as part of an hotkey is it sent to the core as keyboard input.
In addition, a game focus mode was introduced, managed by a toggle hotkey that defaults to scroll lock. In this mode, all keyboard-bound hotkeys are disabled, with the exception of the game focus toggle itself, allowing most key presses to be provided to the core as keyboard input.
Keyboard input is only supported by the poll-based `retro_input_state_t` callback. The event-based `retro_keyboard_callback` is still not supported.
Also updated `libretro.h` to gain access to a more up-to-date list of keyboard keys (`enum retro_key`).
=> add RETRO_DEVICE_KEYBOARD support

src/components/Input.cpp, src/components/Input.h, src/libretro/Core.cpp, src/libretro/Core.h
allows the core to get the entire joypad state in a single call instead of polling for each button individually.
also updates the `RETRO_ENVIRONMENT_` enum string map for the new enum entries.
=> support RETRO_ENVIRONMENT_GET_INPUT_BITMASKS

src/RALibretro.vcxproj
prevents logging of `[DEBUG]` messages in x64 release.
=> set NDEBUG for x64-release build

src/Application.cpp, src/Application.h, src/Gl.cpp, src/Gl.h, src/GlUtil.cpp, src/RALibretro.vcxproj, src/RALibretro.vcxproj.filters, src/Util.cpp, src/Util.h, src/components/Video.cpp, src/components/Video.h, src/components/VideoContext.cpp, src/components/VideoContext.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
Closes #175.
Besides the hardware rendering, there are also two small bugfixes included (in individual commits).
**add opengl hardware rendering support**
If a core requests opengl hardware rendering, the video module creates a framebuffer according to the core-provided requirements and sets the render texture as its color attachment. The core gets the framebuffer through the `retro_hw_get_current_framebuffer_t` libretro callback.
Every frame, after the core is done rendering, it calls `retro_video_refresh_t` with `data = RETRO_HW_FRAME_BUFFER_VALID`, in which case we just make sure the view is set according to the provided `width` and `height` parameters, instead of placing the contents of `data` into the texture as would happen in a software rendering configuration.
When it's time for …
=> add opengl hardware rendering support

src/Application.cpp, src/components/Audio.cpp, src/components/Audio.h, src/libretro/Core.cpp
fixes #164 
The code was writing a 16-bit 44KHz stereo signal to the audio device. If the audio device was expecting more channels, this resulted in the device getting less data than it expected, so the sample ended too soon. For reasons that are unclear to me, the audio output is largely responsible for the speed of the emulator if the emulator is not limited by the CPU. There doesn't seem to be any sort of timer or sleeping mechanism to ensure the proper framerate is not exceeded.
I've also made a couple of optimizations for the "expected" settings. If the core is providing 44KHz audio, we don't try to resample. I've also removed the code that attempts to dynamically adjust the resample ratio as it doesn't seem to be necessary.
=> handle audio devices with more than 2 output channels

src/components/Config.cpp
fixes an issue where config changes would appear to be lost if immediately reopening the dialog after making them.
the dialog copies the config settings so the controller items can be added. once changes are made, the selection is converted to a value and that was being persisted correctly, but the selected index also needed to be copied back into the original config setting object so the correct item would appear selected the next time the dialog was opened.
=> remember config changes within a session

Makefile, src/Application.cpp, src/Application.h, src/Memory.cpp, src/RALibretro.vcxproj, src/RALibretro.vcxproj.filters, src/States.cpp, src/States.h, src/Util.cpp, src/Util.h, src/components/Config.h, src/main.cpp, src/menu.rc, src/resource.h
Adds a new "Saving Settings" dialog that allows the user to specify if they want to put their SRAM and save state files into subfolders for the current system, core, or game.
The default setting for both is "Saves", which mimics the existing behavior. 
When an existing game is loaded after the settings have been changed, we attempt to detect the files in the old location and prompt the user to move them.
Note: this only detects and moves files managed by RALibRetro. Additional files generated by the core have to be moved manually.
=> Allow subfolders for SRAM and save states

src/Application.cpp, src/Emulator.cpp, src/Emulator.h
The dll is held open when it's in use, so it's impossible to delete or update it. If the user tries to update, they get a generic "cannot unzip" error. If they try to delete it, it acts like it worked, but nothing actually happened.
This changes the behavior such that the user is informed that the core is active when they try to do either, and does not attempt to perform the action.
=> show error when trying to update/delete loaded core

src/RAHasher.cpp, src/Util.cpp, src/Util.h
Addresses comment here: https://github.com/RetroAchievements/rcheevos/pull/72#issuecomment-637764884
> the one caveat to this is that hashing the file from within the directory won't see the subdirectory.
=> convert relative paths to absolute paths before hashing in RAHasher

src/libretro/Core.cpp, src/libretro/Core.h
Removes the stubs for unimplemented `environmentCallback` functions so the `default` case handler will ensure they only get logged once.
I don't remember which core was doing it, but `RETRO_ENVIRONMENT_GET_CURRENT_SOFTWARE_FRAMEBUFFER` was being called every frame and filling the log file with "getCurrentSoftwareFramebuffer isn't implemented".
=> ensure unimplemented function calls are only logged once

src/components/Config.cpp, src/components/Config.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
Implements the `RETRO_ENVIRONMENT_SET_CORE_OPTIONS` environment callback so cores can provide user-friendly labels for their options.
Here's the Beetle PSX settings dialog before and after:
Most of the changes are whitespace and capitalization, but I've highlighted the CPU Dynarec field where you can see the options are (hopefully) clearer now.
=> allow core to provide labels for config options

src/components/Config.cpp, src/components/Config.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
Allows the core to specify that it wants to hide specific options. The most obvious use of this is the beetle PSX core hiding PAL options for NTSC games and vice versa.
=> implement RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY

src/Application.cpp, src/Application.h, src/States.cpp, src/States.h, src/Util.cpp, src/Util.h
closes #188 
The default value for this option is "None", as writing to disk has inherent overhead that could affect emulator performance. To minimize that impact, the SRAM is only written to disk if it has changed since the last interval. This requires keeping a second copy of the SRAM in memory for the comparison. A second copy is not kept if the interval is "None".
Additionally, the smallest interval is 10 seconds. It seems unlikely that the catastrophic error would occur immediately after using an internal save point, and if it did, it would likely be immediately, so any interval would be too long.
=> allow user to specify interval for flushing SRAM to disk

src/Application.cpp, src/libretro/Core.h
Fixes an issue where some state can leak from a previously loaded game into the newly loaded game.
We already do this when opening items from the recent menu and for disc-based games. This just extends the behavior for all games opened from the "Load Game..." menu item.
Tested by loading an MSX game, then loading a different MSX game. Without the change, the second game would crash the emulator, fail to load, or corrupt the image.
=> reload core when loading new game

src/Application.cpp, src/Memory.cpp
fixes a crash when resetting a 3DO game, which returns a new pointer for the exposed memory regions.
=> remap memory when game is reset

src/Application.cpp, src/Gl.cpp, src/Gl.h, src/components/Video.cpp, src/libretro/BareCore.cpp
Some of the changes to support hardware rendering require OpenGL 3.0, but not all of our userbase is running OpenGL 3.0. This isolates the 3.0 features to hardware rendering mode, allowing those users access to the same set of functionality previously available to them. They will receive an error trying to activate hardware rendering mode.
Also fixed the log message that reports the current OpenGL version to actually report the current version instead of the version we asked SDL to get (which was the default - 2.1).
=> fix missing video when running on OpenGL 2.0

src/States.cpp, src/States.h, src/Util.cpp, src/libretro/Core.cpp
Fixes an error where SRAM would silently not be written when using an SRAM path other than `Saves` and not migrating data. Migrated data would correctly create the subfolder, but if no data was migrated, the folder would not exist and the save would fail.
=> ensure sram subfolders exist before trying to write file

src/components/Video.cpp
fixes issue where switching from a hardware rendered core to a non-hardware rendered core causes the image to be inverted and zoomed in.
caused by #211 - the vertex buffer was not being destroyed when switching to a non-hardware rendered core.
=> reset vertex array when switching from hardware to non-hardware mode

src/Application.cpp
Fixes the filter for the "Save State..." and "Load State..." dialogs so only ".state" files are shown.
=> initialize file filter properly for custom state files

bin/Cores/cores.json
I've tested both cores with all applicable systems and can't see any issues.
=> Add Mesen and Mesen-S to supported cores

etc/CopyDLLs.bat, src/RALibretro.vcxproj
fixes "unable to load core" error when running from build directory on clean checkout.
#210 removed several DLLs from the repository, but at least a couple of them are required by the cores. Attempting to load a core without them present generates an "unable to load core" error. Rather than add them back into the repository, this attempts to copy them from the source (mingw installation).
For users who don't have mingw installed, the releases can be downloaded from the website and the DLLs copied from there.
=> also copy mingw dlls for core dependencies

src/components/Audio.cpp, src/components/Audio.h, src/libretro/Core.cpp, src/speex/version.txt
This fixes low-level background static and occasional clicking in the Snes9x core.
The first issue is that we were using a single-channel resampler to resample both channels, so the interleaved data was becoming slightly entangled. I tried using the `speex_resampler_process_interleaved_int` function, and that eliminated the background static, but the occasional clicking persisted. 
Apparently, speex's resampler can only carryover state from one call to the next for a single channel (whichever channel was the last processed). To address that, I ended up creating two resamplers - one for each channel, and with some additional setup, I'm able to still process the interleaved data without having to deconstruct and reconstruct it.
Also added some logic to prevent an infinite loop if the FIFO …
=> resample each audio channel separately

src/Application.cpp, src/Fsm.cpp, src/Fsm.fsm, src/Fsm.h, src/components/Config.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
Whether or not fast forwarding is currently enabled is now stored in the `Config` object so it can be polled by the core. The `GameTurbo` state has been eliminated. It's now handled within the `GameRunning` state. This has the benefit of remembering if turbo was enabled when transitioning through other states (like opening/closing the overlay).
=> implement RETRO_ENVIRONMENT_GET_FASTFORWARDING

src/Application.cpp, src/Fsm.cpp, src/Fsm.fsm
Ensures the overlay is shown/hidden correctly when using the Pause toggle button/menu options.
not paused
* pause toggle -> pause if not hardcore, ignore if hardcore
* overlay toggle -> pause and show overlay
* pause menu -> pause if not hardcore, pause and show overlay if hardcore
* resume menu -> not available
paused (not available in hardcore)
* pause toggle -> unpause
* overlay toggle -> show overlay
* Note: because the overlay toggle switches to overlay mode when toggling the overlay while paused, toggling the overlay again will both close the overlay and resume gameplay (instead of returning to paused mode).
* pause menu -> not available
* resume menu -> unpause
overlay visible
* pause toggle -> unpause and hide overlay
* overlay toggle -> unpause and hide overlay
* pause menu -> …
=> fix interaction of Show Overlay and Pause toggle behaviors

bin/Cores/cores.json
This will reduce the dependence of both testers and devs on custom core sets being passed around. I also split GB and GBC extensions for relevant cores, to reduce memory mismatch issues from incorrect system selection.
I tried to be thorough, including cores not currently being built successfully. I can update this to remove things like MAME variants if desired, but it seemed more complete was better than less.
=> Added unsupported cores in a disabled state

src/components/Input.cpp
fixes an issue where the core reading axis data for secondary controllers would get back non-zero values if the player didn't have anything mapped for them.
=> ensure unused controller definitions are zero'd out

src/components/Config.cpp, src/components/Input.cpp, src/components/Input.h
Fixes #241 
The core settings dialog was filtering the input selections to JOYPAD and ANALOG, as those were originally the only things RALibretro supported. When MOUSE and KEYBOARD were added, the filter was not updated.
While this change does allow selecting the Mouse as an input device, the libretro mouse interface uses relative positions, which means the in-game pointer won't line up exactly with the Windows pointer, so the experience of actually using the mouse for an input device is kind of clunky. We recommend players use the "touch" pointer type in the NDS cores because it uses absolute positions and provides a much better experience. The Beetle PSX core doesn't seem to have a "touch" or "pointer" mouse mode, though it does have a "touch" gun mode.
=> allow all controllers to be selected in core config dialog

src/Application.cpp, src/components/Video.cpp, src/components/Video.h
Fixes #244 
Adjusts the mouse position calculation algorithm to account for the actual scaled view size (instead of using the window size). In addition to fixing the behavior when Preserve Aspect Ratio is enabled and the window aspect ratio does not match the view aspect ratio.
This also improves the functionality when using "mouse" input mode, and fixes a miscalculation of the mouse Y location when the screen is rotated 270º.
=> fix calculation of mouse position when perserve aspect ratio is enabled

src/Application.cpp, src/KeyBinds.cpp, src/KeyBinds.h
Closes #230 
Adds a bindable hotkey for Reset and updates the layout of the dialog to support two columns for non-savestate hotkeys:
=> add hotkey for reset

bin/Cores/cores.json
Closes #92 
Tested with a headered rom. It was correctly identified, and the core seems to support all the other requirements.
=> enable Beetle Lynx as a supported core for Atari Lynx

src/About.cpp, src/Application.cpp, src/RAHasher.cpp, src/components/Logger.cpp, src/components/Logger.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
Any errors logged by the core while loading a game will now be reported in the "Game load error" dialog.
If no errors are logged, the existing dialog will be shown with a generic "Please ensure that required system files are present and restart." message.
=> capture and report core errors when loading game

Makefile, src/Application.cpp, src/Application.h, src/RALibretro.vcxproj, src/RALibretro.vcxproj.filters, src/cheevos_libretro.c, src/cheevos_libretro.h, src/components/Config.cpp, src/components/Config.h, src/main.cpp
Adds validation checks for unapproved core settings when loading a game, when changing core settings, and when enabling hardcore mode.
Similar changes were made in RetroArch via https://github.com/libretro/RetroArch/pull/11476
=> disable hardcore mode when certain core options are enabled

src/Application.cpp, src/components/Config.cpp, src/components/Config.h, src/components/Logger.cpp, src/components/Logger.h
supports #253
The log file was being opened before calculating the root folder. I've modified the logic to calculate the root folder first, and write the log fie there.
=> calculate root folder before opening log file

src/Memory.cpp, src/Memory.h
supports display of unsupported memory regions (see https://github.com/RetroAchievements/RAIntegration/pull/669)
=> register invalid banks without a read function

src/Memory.cpp
Changes made for #258 can register multiple banks with the DLL, but all banks were using the same read/write functions, so all memory was coming out of the first bank. The callback functions registered with the DLL are passed an offset within the bank, so the logic has to offset the read/write to accommodate.
=> addresses passed to read/write functions are relative to the start of the bank

src/Application.cpp
When paused, the main loop ran at full speed, using up a whole cpu core.
This commit puts a 10ms sleep into the loop when paused, bringing cpu use down to virtually 0. The sleep duration is small enough for the overlay to be navigable without noticeable delay.
=> avoid 100% cpu core use while paused

src/States.cpp, src/States.h, src/Util.cpp, src/Util.h
Supports the new save state container format implemented in RetroArch. Allows achievement state to be stored directly in the save state file instead of in a neighboring file. Also allows the frame buffer to be stored in the state file (closes #125).
Legacy formatted files (with their companion .rap and .png files) are still supported. Newly created files will always be in the new format.
Additionally, the filename format has been changed from "GameName.001.state" to "GameName.state1" to match RetroArch, making it easier to share files between them. Existing ".XXX.state" files will still be recognized when loading the built-in states. Saving to a built-in state slots will generate a ".stateX" file and remove the ".XXX.state" files.
RZIP (compresses RetroArch) save states are still not …
=> Support for RASTATE state files

src/Util.cpp, src/components/Logger.cpp
fixes a bug introduced by #256 where the log could not be opened if run from within a path containing non-ASCII characters.
=> fix opening log file in unicode path

src/Application.cpp, src/Application.h, src/KeyBinds.cpp, src/KeyBinds.h, src/menu.rc, src/resource.h
When the menu gets wrapped, the calculation for available space is wrong. This is happening in the SDL library, so it's not entirely clear why, but it's easy enough to get the actual size of the window and resize it again if it's not the expected size.
Also adds a Resize to 5x option for systems with very small resolutions (like GameGear).
=> account for multi-line menu when resizing window 1x on lower-resolution systems

bin/Cores/cores.json
=> add QuickNES as a supported core

src/Application.cpp, src/components/Video.cpp, src/components/Video.h
closes #266 
The "Video" settings menu is now global. "Keep Aspect Ratio" and "Linear Filtering" will be applied to (and remembered for) all cores. "Rotation" is not remembered, and is reset to "None" whenever a core is loaded.
=> make video settings global

src/components/Input.cpp
fixes #283
the fbneo core doesn't define input devices until after a game has been loaded. if you select a device that's not in the initial menu (i.e. RetroPad), attempting to read from the non-existant device was throwing an exception.
=> prevent exception when configuration file specifies a device index that hasn't yet been defined

src/RALibretro.vcxproj, src/components/Video.cpp
The `VecX` core's hardware rendering mode was not working. A single frame was displayed before the screen turned black, even though the game could be heard running in the background.
In `Video::ensureVertexArray`, a buffer is bound to the VAO upon creation so that it doesn't have to be explicitly bound everytime we draw. It seems, however, that even though the `GL_ARRAY_BUFFER` bind affects the currently bound VAO, it also affects global state. To avoid this conflicting with a core's own rendering, the buffer must be unbound (after the VAO itself is unbound, to keep the association between the two... not weird at all).
There was also a minor issue during the boot of the core, in which it called the set-geometry callback with a max width and height of 0, causing an error: `ensure …
=> unbind GL_ARRAY_BUFFER to avoid conflicts with the core's rendering

bin/Cores/cores.json
From some quick tests everything looks identical to GPGX. I see no specific reason for the core to be unsupported at this point. The m3u support is brand new, via libretro/picodrive#154. Of note, this core will be required to develop any 32X CD games.
=> Add m3u to picodrive and mark supported for Sega CD

src/Application.cpp, src/Application.h, src/KeyBinds.cpp, src/KeyBinds.h, src/States.cpp, src/components/Audio.cpp, src/components/Audio.h, src/components/Config.cpp, src/components/Config.h, src/libretro/Components.h, src/libretro/Core.cpp, src/menu.rc, src/resource.h
Adds options for fast forward rate (2x-10x) and playing audio while fast forwarding (closes #243).
Note: Fast forward rate just indicates how often to render a frame. It doesn't guarantee the specified speed up. For example, at 10x, only one frame is rendered out of every 10. Depending on the complexity of the core and the power of your computer, it may take as long as rendering four or five frames at normal speed, resulting in the appearance of double speed instead of 10x.
=> Add Emulator Settings dialog

src/Memory.cpp
fixes issue where freeintv core (using new DLL) duplicates the first 128 bytes.
=> first valid region may not be block 0

src/Application.cpp, src/Application.h, src/CdRom.cpp, src/CdRom.h
also addresses an issue if the paths exceeded 128 bytes.
=> strip paths from items in m3u when populating cd menu

src/States.cpp
Fixes issue reading SRAM for Sonic Delta 40MB. The amount of SRAM requested by the core when starting the game greatly exceeds the amount provided when exiting the game. The code treated this as an error and ignored the SRAM when reloading the game.
RetroArch does not treat this as an error and only loads the amount available. I have made similar changes here.
=> allow sram size mismatch

src/Application.cpp, src/Util.cpp, src/Util.h
fixes an issue where using the manual save state feature would not correctly append the extension if the filename (or path) contained a period.
=> let windows manage default file extension; add all files to open state dialog

src/libretro/Core.cpp, src/libretro/Core.h
RetroArch immediately passes any audio provided by the core to the audio device. RALibretro buffers several chunks of audio before passing the data to the core to minimize crackling due to resampling such small samples.
libretro cores are throttled entirely by how quickly the audio data is processed. If the audio device buffer is full, the code _will wait_ in the audio providing code until the audio device has processed some of the buffered data and there's space to queue the new data.
RALibretro uses a large enough buffer that an entire frame's worth of audio can be captured before it's flushed to the audio device. Despite pushing the same amount of data to the audio device, doing so outside of the `core.step` function appears to affect the timing of some cores (notably PPSSPP and …
=> use smaller buffer for audio resampling

src/Application.cpp, src/Application.h, src/libretro/Core.cpp, src/libretro/Core.h, src/libretro/libretro.h
allows the core to request that the frontend manage the game data instead of requiring the core create its own copy.
=> implement RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE

src/Application.cpp, src/components/Logger.cpp
Adds an `HHMMSS.xxx` prefix to each line of the log as it's written to the file. These timestamps are not included in the about dialog's running log.
```
181632.438 [INFO ] [APP] RALibretro version 1.3.7.4-x64 starting
181632.439 [INFO ] [APP] RALibretro commit hash is 516f7754d9865ee0d9d077ade60ab2c894c445c6
181632.439 [INFO ] [APP] Current time is 08/29/21 18:16:32 Mountain Daylight Time
181632.441 [INFO ] [CFG] Root folder:        E:\Source\RetroAchievements\RALibretro\bin64\
181632.441 [INFO ] [CFG] Assets folder:      E:\Source\RetroAchievements\RALibretro\bin64\Assets\
181632.441 [INFO ] [CFG] Save folder:        E:\Source\RetroAchievements\RALibretro\bin64\Saves\
181632.441 [INFO ] [CFG] System folder:      E:\Source\RetroAchievements\RALibretro\bin64\System\
181632.441 [INFO ] …
```
=> add timestamps to log

bin/Cores/cores.json
I opted to leave SwanStation disabled, since users will have to add the core manually to work with it anyway.
=> Fix duckstation name in cores.json, add citra 2018

src/libretro/Core.cpp, src/libretro/Core.h
Prevents crash when loading melonDS core (core still crashes when unloading the game). 
Also leveraged by the Beetle SuperGrafx core (though it will fallback to an internal implementation if not provided by the frontend).
=> add support for RETRO_ENVIRONMENT_GET_VFS_INTERFACE

src/components/Config.cpp, src/components/Config.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h
Supports categories for core settings (when implemented by the core).
Before:
After:
=> add support for RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2

src/Application.cpp, src/Hash.cpp, src/Hash.h, src/RA_Implementation.cpp
Simplifies the process of loading discs not associated with the game for games like Vib-Ribbon and Monster Rancher.
Makes three changes:
* Selecting an audio CD from an .m3u will not unload the achievement set. Previously the achievement set was unloaded.
* Selecting a disc associated to a known game will not unload the achievement set. Previously the achievement set was replaced with the achievements for the alternate game.
* Selecting a disc not associated to a known game will not unload the achievement set. However, as an unknown disc may just be a modified version of the base game, so doing so is not allowed in hardcore. Previously the achievement set was unloaded.
=> allow non-game CDs to be loaded without unloading game

bin/Cores/cores.json, src/Application.cpp, src/libretro/Core.cpp
RetroArch provides a few environment callbacks that are specific for RetroArch. 
https://github.com/libretro/RetroArch/blob/2b87cd931372f775c64f25ed2b04eea72da87df7/retroarch.h#L46-L73
This adds logging messages to report these as unsupported callbacks.
=> log when core tries to call a RetroArch-specific callback

bin/Cores/cores.json
SwanStation is the libretro fork of DuckStation. The DuckStation build is no longer being maintained.
=> deprecate duckstation

src/Application.cpp, src/Application.h, src/libretro/Core.cpp, src/libretro/Core.h
Both PPSSPP and Flycast sometimes only generate 30 frames of video per second, even though the core says it's supposed to be generating 60 fps. This causes RALibretro to drop frames trying to bring the framerate back up to the specified level (see #104).
PPSSPP has a workaround for this: "duplicate frames in 30hz", but Flycast does not.
RetroArch seems to derive its actual framerate purely from the speed at which the audio is generated (see also #300). Instead of relying on the fps calculation to determine if frames need to be dropped, this implementation relies on the ability of the core to generate audio quicker than it can be consumed. Similar to #104, if the audio is not being generated fast enough, vsync will be disabled. If it still is not being generated fast enough, the user will …
=> eliminate attempt to match core-specified framerate

src/libretro/Core.cpp, src/libretro/Core.h
Prevents crash if core expects a handler to be registered.
=> provide dummy handler for RETRO_ENVIRONMENT_GET_LED_INTERFACE

src/Application.cpp
prevents a crash using the core settings dialog if the core hasn't initialized its memory regions
=> don't refresh memory map unless game loaded

.github/workflows/c-cpp.yml, .gitignore, Makefile.RAHasher
Improving the github workflow to automatically deliver RAHasher for Linux in the releases page **when a new tag is created**.
=> deliver RAHasher for Linux on releases page

src/Application.cpp, src/KeyBinds.cpp, src/KeyBinds.h
It would be preferable to just say "Game Focus On" or "Game Focus Off" when using the button like RetroArch does, but RAlibretro still doesn't have any way to show on-screen messages (see #2)
=> add Game Focus indicator to titlebar

src/Memory.cpp
Allows DLL to read chunks of memory from the application instead of just one byte at a time. Should provide minor performance improvement when memory inspector is open and when performing searches over large amounts of memory.
=> support for RA_InstallMemoryBankBlockReader

src/Application.cpp, src/Emulator.cpp, src/Emulator.h
Implements #338
If more than 20 items would appear in the systems menu, then an additional level is added for manufacturers.
The same grouping is provided as on the site, but the items are alphabetical.
=> add submenus for manufacturers when list becomes long

bin/Cores/cores.json
It looks like picodrive added gamegear support over a year ago: https://github.com/libretro/libretro-core-info/commit/161089447bf923f34ee877098dbf127cc2e43d7f
Brief testing suggests the core is functional, though discord discussions suggest it may have issues (not just with Game Gear). This PR just add it to the list of available cores for GameGear in RAlibretro.
=> enable picodrive for gamegear

src/KeyBinds.cpp, src/KeyBinds.h, src/libretro/Core.cpp
Splits the "Left Analog X", "Left Analog Y", "Right Analog X", and "Right Analog Y" input bindings into "Left Analog Left", "Left Analog Right", "Left Analog Up", "Left Analog Down", "Right Analog Left", "Right Analog Right", "Right Analog Up", and "Right Analog Down", allowing keys to be bound to each direction.
Also adds import/export buttons to the dialog (closes #356).
=> Support for binding analog sticks to keyboard

src/Gl.cpp, src/Gl.h, src/components/Video.cpp, src/libretro/Core.cpp
This PR fixes rendering in dolphin by calling `glBindSampler(0, 0)` in `Video::postHwRenderReset()`
=> Fix rendering in dolphin

src/KeyBinds.cpp, src/KeyBinds.h
example:
```
event         | held | old    | new
press left    | L    | -32767 | -32767
press right   | LR   | +32767 | +32767
release right | L    | 0      | -32767
press right   | LR   | +32767 | +32767
release left  |  R   | 0      | +32767
press left    | LR   | -32767 | -32767
release right | L    | 0      | -32767
release left  |      | 0      | 0
```
=> fix axes being set to 0 when both keys are held and one is released

src/Application.cpp, src/components/Video.cpp, src/components/Video.h, src/components/VideoContext.cpp, src/components/VideoContext.h, src/libretro/Components.h, src/libretro/Core.cpp
Some rendering issues can be caused by the OpenGL state changes made by the frontend. Using separate OpenGL contexts for the core and for the frontend prevents these kinds of issues.
Before:
After:
More rendering issues are caused by leftover OpenGL state when switching games. Destroying and re-creating the OpenGL state on core shutdown resolves this.
Loading Metroid Prime, then Mario 64
Before:
After:
=> Fix rendering issues with context management

src/HashCHD.cpp
Pick up upstream fixes for 64-bit fseek and double close on error (and more)
Fixes #368.
* The 64-bit fseek issue causes the "Could not open track" failure
* The double close on error causes the "no output" failure
=> update to latest libchdr

src/Application.cpp, src/Application.h, src/components/Config.cpp, src/components/Config.h, src/components/Dialog.cpp, src/libretro/Components.h, src/libretro/Core.cpp, src/menu.rc, src/resource.h
Closes #264
Adds a new option (off by default) to enable joystick input when the main window doesn't have focus.
=> Background input

bin/Cores/cores.json
Fixes a JSON parse error that prevents the Yabause core from being visible.
=> add missing comma

src/Application.cpp, src/Application.h
prevents visible jump as window goes from center of screen to the remembered location
=> load configuration before showing window so it can be created at the remembered location

src/Gl.cpp, src/Gl.h, src/components/Video.cpp, src/components/Video.h
This prevents issues with core shutdown caused by OpenGL errors that occur within a core
=> Log and ignore OpenGL errors from core

src/Application.cpp
setting is functionally remembered, but not visually.
=> fix background input check mark not showing after restarting application

src/States.cpp
Fixes an issue where achievement hits persist when loading a savestate that was created by RetroArch with achievements off.
=> reset runtime if loading state with no achievement data

src/Application.cpp
Fixes a long-standing discrepancy introduced by #265. 
> Additionally, the filename format has been changed from "GameName.001.state" to "GameName.state1" to match RetroArch
However, the Load State dialog was not updated to match numeric state files, so the user has to select "All Files" to find them.
This fixes that.
=> support for numeric prefixes on state files in load state dialog

src/Application.cpp, src/Emulator.cpp, src/Emulator.h
When selecting a core from the "Select Core" menu, it's last updated timestamp will be compared to the current time. If the timestamp is more than 365 days old, a popup will appear informing the user that they're on an old core:
Clicking 'Yes' will open the Manage Cores dialog where the user can download the newest available version. Clicking 'No' will dismiss the dialog and the old core will continue to be used.
The check does not occur when opening games from the "Load Recent" menu as upgrading the core may cause save states to become invalid.
=> add warning when loading old core

Makefile, src/Application.cpp, src/Application.h, src/RALibretro.vcxproj, src/RALibretro.vcxproj.filters, src/components/Audio.cpp, src/components/Microphone.cpp, src/components/Microphone.h, src/libretro/Components.h, src/libretro/Core.cpp, src/libretro/Core.h, src/libretro/libretro.h
Seems functional, but a little more sensitive than the RetroArch implementation. I didn't see anything in the SDL documentation for tweaking the sensitivity.
=> implement RETRO_ENVIRONMENT_GET_MICROPHONE_INTERFACE

src/Application.cpp, src/RAHasher.cpp
Verbose mode and system detection are not supported when hashing multiple files.
```
E:\Source\RetroAchievements\RALibretro>bin64\RAHasher.exe 72 E:\Games\RetroAchievements\ROMs\Other\WASM\*
f4d55cbcb51b2c11010b7999fd913cec antcopter.wasm
f4d55cbcb51b2c11010b7999fd913cec antcopter.zip
04afe658b3c9e2e61dbef7897d604adc miku-15.wasm
7e372d919d84e94f14c71222f1f372f2 the-legend-of-geml-awakening.wasm
06c02089c236dff8af5ca6fe42c9eab6 to-the-core.wasm
04d126cfe702b2d2114b190c11536302 wormhole.wasm
```
```
$ bin64/RAHasher 7 ~/roms/*.nes
25cf03eb7ac2dec4ef332425c151f373 Dragon Warrior (U).nes
811b027eaf99c2def7b933c5208636de Super Mario Bros. (W) [!].nes
```
=> RAHasher: hash multiple files via wildcards

bin/Cores/cores.json
camera interface issue was resolved (a couple years ago)
=> enable GB/GBC for mGBA core

src/libretro/Core.cpp
Fixes crash using latest Genesis Plus GX core for non-CD games.
=> allow core to deregister disk control interface

bin/Cores/cores.json, src/libretro/Core.cpp
The [header file](https://github.com/libretro/RetroArch/blob/a3f13b226874121422c8f967d69950809b8670ff/libretro-common/include/libretro.h#L2800-L2812) says that retro_vfs_seek_t should return the new position, or -1 on error (this is true prior to the [recent doc expansion](https://github.com/libretro/RetroArch/blob/a417f744766347d8bd8e2ff1e8169479ec0af22e/libretro-common/include/libretro.h#L1943-L1945) as well).
But the implementation (at least for unbuffered files [calls fseek](https://github.com/libretro/RetroArch/blob/master/libretro-common/vfs/vfs_implementation.c#L224-L245)), which returns 0 on success, not the offset.
The quasi88 core is treating [any non-zero return value as a failure](https://github.com/libretro/quasi88-libretro/blob/ff94d9d2884d71580c163fcd71b6850c0f393f44/src/fdc …
=> make vfs_seek behave like fseek

Makefile, Makefile.RAHasher, Makefile.common
The included changes to `Makefile`s were the only required ones to make the build process work on `arm64`.
As `-march=armv8-a` was invalid when trying to build RALibretro, I have only added ARM64 support for `RAHasher`.
Building process can be tested using the following Dockerfile:
```dockerfile
FROM debian:12
RUN apt-get update && apt-get install -y --no-install-recommends \
build-essential \
zlib1g-dev
WORKDIR /src
COPY . .
RUN make HAVE_CHD=1 -f ./Makefile.RAHasher
```
Using the following command:
```shell
docker buildx build -t rahasher:arm --platform linux/arm64 .
```
=> Allow RAHasher be compiled for arm64 architecture

src/Application.cpp, src/Application.h, src/components/Config.cpp, src/components/Config.h, src/components/Video.cpp, src/components/Video.h, src/libretro/Components.h, src/libretro/Core.cpp
Adds an indicator in the upper right corner of the screen when the emulator is paused or in turbo mode.
If undesirable, this can be disabled in the Emulator Settings dialog:
=> Add indicator for pause/fast forward

src/Application.cpp, src/Application.h, src/KeyBinds.cpp, src/KeyBinds.h, src/libretro/Core.cpp, src/libretro/Core.h
implements #416 
Rather than support jumping to specific disks, I've implemented it such that there is one hotkey to eject/insert the disc, one for next disc, and one for previous disc.
The following are the defaults, but can be changed by the user. I chose to put eject in the middle to eliminate the need to reach over prev to get to next:
* Alt+0: Previous disk
* Alt+-: Eject/Insert
* Alt+=: Next disk
=> add hotkeys for changing disks

src/Application.cpp, src/KeyBinds.cpp, src/KeyBinds.h
implements #26 and #364
Loading/saving custom states has been mapped to F12 (load) and Shift+F12 (save). Previously F12 was mapped to save selected state, but that has been changed to Shift+F11. Players upgrading to this version will have two functions mapped to F12.
The next/previous state hotkeys will now go all the way up to 99. You can still only get to the first 10 states via the 1-0 keys. To get to 11-99, you must use the next/previous state hotkeys.
To load/save the selected state, press F11 (load) or Shift+F11 (save). Loading states 1-10 can still be done with the F1-F10 keys, and does not change the selected state, so you can alternate between states 3 and 14 by selecting state 14, pressing F3 to load state 3 and F11 to load state 14.
=> allow next/prev state to go up to 99; add hotkey for save/load custom state

src/Application.cpp, src/Fsm.cpp, src/Fsm.fsm
Fixes an issue where the pause indicator remains on screen when the emulator is reset. Rather than remove the pause indicator, I felt it was more appropriate to not unpause the emulator when resetting. This allows developer to debug memory state as the emulator is reset.
=> don't unpause emulator when resetting

src/HashCHD.cpp
Fixes https://github.com/RetroAchievements/RAIntegration/issues/1142
The logic for hashing a Dreamcast CD looks for the executable in track 3. If it's not found in track 3, it looks in the last data track. In both cases, the code just says "open track 3, fetch data at sector Y, if that fails, open track LAST, fetch data at sector Y".
When processing a CHD, we weren't checking if sector Y existed in track X, so it would blindly go find data some Y sectors after the start of track 3. Because of padding between tracks, this wasn't the executable and the hash would be wrong.
=> don't read past end of CHD track

src/RAHasher.vcxproj, src/RALibretro.vcxproj
The copy DOS command will not work with unquoted paths with `+` characters; it tries to interpret them as additional source files.
I ran into this issue with a `C++` folder name.
=> Fix copy command for paths with + char

bin/Cores/cores.json, src/Application.cpp, src/Emulator.cpp
The fceumm and mesen cores.json changes are temporarily disabled until a new DLL can be released as the dll will complain about a mismatch between the client registering FDS memory and the game being returned as NES. Users wanting to test the functionality can remove the "platforms:none" from the "systems:81" entries if they have access to an updated DLL.
https://discord.com/channels/310192285306454017/1124566547797655692/1310992211730763888
https://discord.com/channels/310192285306454017/1124566547797655692/1311347053934149732
=> preparation for split of FDS from NES
