src/Emulator.cpp

Also removed the code related to the PlayChoice-10 and trainer flags for NES header hashing as discussed after merging #49

Ignore header when hashing SNES ROMs

---

etc/MakeGitCpp.bat
src/RALibretro.vcxproj

supports https://github.com/RetroAchievements/RAIntegration/issues/229

also generate gitVersion when generating Git.cpp in MSVC build

---

src/Application.cpp

use getSystem() after game loaded by core - closes #65

---

src/Application.cpp

ensures proper disc is selected after loading a save state

update CD-ROM menu after loading state

---

src/Emulator.h

Adds WonderSwan to src/Emulator.h

Adds WonderSwan

---

bin/Cores/cores.json

Adds the Beetle Cygne core (WonderSwan) to bin/Cores/cores.json

Adds Beetle Cygne (WonderSwan)

---

src/Hash.cpp

allows hashing of PSX games that don't have a SYSTEM.CNF (mostly unlicensed games).

handle PSX.EXE (no SYSTEM.CNF)

---

src/Application.cpp
src/Application.h
src/components/Input.cpp
src/components/Input.h
src/components/Video.h
src/libretro/Core.cpp

add RETRO_DEVICE_MOUSE support

---

src/Application.cpp
src/KeyBinds.cpp
src/KeyBinds.h

Ctrl+R to rotate right
Ctrl+Shift+R to rotate left

add keybinds for screen rotation

---

src/Application.cpp
src/menu.rc

better handling when no cores are available

---

src/Util.cpp

ensure OPENFILENAME struct is fully initialized

---

src/libretro/Core.cpp

don't wait indefinitely for core to generate sound

---

src/components/Dialog.cpp

properly close dialog window when using ESC hotkey

---

src/Application.cpp

Easily reproduced using `International Sensible Soccer (Europe) (En,Fr,De,It)`:
* Create save states at main menu and in game.
* Toggle between states
NOTE: video stops updating.
The problem is that the in-game resolution is 320x240, but the main menu resolution is only 320x224. When attempting to load the larger image into the smaller frame buffer, the frame buffer gets corrupted and stops updating.
This adds logic to truncate the larger image when loading it. If paused, this will cause part of the image to not be visible on screen, but the first frame processed after loading the state will correct that.

prevent memory corruption if save state image is larger than frame buffer

---

bin/Cores/cores.json

add support for vecx core

---

bin/Cores/cores.json

add parallel_n64 as a supported core

---

bin/Cores/cores.json
src/libretro/Core.cpp

closes #130. opera is the new name for 4do

add opera as a supported core

---

bin/Cores/cores.json
src/Application.cpp

add vba-m as a supported core

---

bin/Cores/cores.json

most of the mednafen cores are now reporting themselves as "Beetle"

update mednafen core names

---

src/Memory.cpp

fixes base address calculation for memory blocks labelled as VIRTUAL_RAM or HARDWARE_CONTROLLER when core doesn't implement memory map

improve support of SYSTEM_RAM mapping when rcheevos has more detail

---

src/Application.cpp
src/Application.h
src/main.cpp

Adds a SIGABRT handler and a couple try/catch statements to try to more gracefully shutdown when an unhandled exception occurs. Most importantly, it attempts to flush the log file just in case something useful may have been captured.
It does not attempt to fix any errors, and unfortunately, cannot provide any additional information about the exceptions that would be useful for debugging. In most cases, to get any sort of useful debugging information, the user would have to be running in a debugger, or have a debugger available to attach to the process when the error occurs.

Attempt to more gracefully shutdown when an unhandled exception occurs

---

src/libretro/Core.cpp

Multi-threaded cores expect to be able to interact with the frontend from all threads. `InstanceSetter` was using a thread_local variable that cleared out the reference when the call into the core completed. Removing the thread_local helped a little, but since we can't control when the other threads try to access the frontend, the reference can't be limited to the when we're calling into the core. As a result, I've replaced the thread_local variable with a global variable, which is assigned to the `Core` instance when it's initialized. Additionally, `InstanceSetter` has been eliminated as we want the value to be set for the life of the `Application`.
This prevents crashing in PPSSPP, flycast, and dolphin, though they all have other issues that still need to be addressed. PPSSPP and …

replace InstanceSetter with global reference to core

---

bin/Cores/cores.json

fix reversed system IDs associated to VBA-M core

---

src/KeyBinds.cpp

There's been a couple of incidents recently where people have complained that one or more keys/controller buttons have not been functioning as a result of having that key/controller button mapped to multiple actions. This attempts to inform the user when they do that under the assumption that they might be able to identify and correct the issue themselves.
While internally, we know what action is associated to the duplicate binding, there's no direct mapping from that to a user-friendly description that can help the user identify which other binding is already mapped to the selected input, so the dialog just shows a generic warning. The user will have to identify the conflicting binding themselves.

show warning when binding is associated to multiple actions

---

bin/Cores/cores.json

* Enabled FreeIntV
* Fixed bsnes HD beta filename
* Added GG/SG-1000 to SMS Plus GX

Cores.json updates

---

bin/Cores/cores.json
src/libretro/Core.cpp
src/libretro/Core.h

add SwanStation as a supported core

---

bin/Cores/cores.json

* Remove genesis console ID from Gearsystem (not supported)
* Add m3u to Genesis Plus GX

Updates to cores.json

---

.gitmodules
Makefile
Makefile.RAHasher
Makefile.common
RALibretro.sln
bin/Cores/cores.json
src/Hash.cpp
src/HashCHD.cpp
src/Memory.cpp
src/RAHasher.cpp
src/RAHasher.vcxproj
src/RAHasher.vcxproj.filters
src/RALibretro.vcxproj
src/RALibretro.vcxproj.filters
src/libchdr.vcxproj
src/libchdr.vcxproj.filters

CHD support

---

src/States.cpp
src/States.h
src/libretro/Core.cpp
src/libretro/Core.h

capture and report core messages when load state fails

---

src/libretro/Core.cpp

From the "documentation" for `retro_memory_descriptor.len`:
> Can be zero, in which case it's assumed to be infinite (as limited by 'select' and 'disconnect').
Fixes memory not being exposed in Snes9x 2010 core for most games.

If core provides memory descriptor pointer without length, calculate length

---

src/KeyBinds.cpp

Hoping to address https://discord.com/channels/310192285306454017/353363923333808128/1067671611072856154

add warning when input window doesn't have focus

---

src/Hash.cpp

https://discord.com/channels/310192285306454017/310195854642249728/1074725906234495066

prevent infinite recursion if core says the zip file is the first disc

---

src/HashCHD.cpp

improve calculation of CHD sector layout

---

src/components/Video.cpp

Fixes the primary issues in #379

fix to #367 for screenshots and savestates

---

src/Application.cpp
src/components/Input.cpp
src/components/Input.h

Message is only shown if the controller has active bindings

show message when controller is connected/disconnected
